server:
  port: 8084

debug:
  enable: true

spring:
  application:
    name: babynotificationhub

  mail:
    host: smtp.gmail.com
    port: 587
    username: moviesrental.notificationhub@gmail.com
    password: 1005717745
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true

eureka:
  client:
    instance.preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true

    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka