server:
  port: 8084
  tomcat:
    max-swallow-size: 100MB

debug:
  enable: true

spring:
  application:
    name: babynotificationhub

  mail:
    host: smtp.gmail.com

    port: 587

    username: moviesrental.notificationhub@gmail.com

    password: qbqyjzgpvnxqxhks

    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 100MB

eureka:
  client:
    instance.preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true

    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka