server:
  port: 8081

debug:
  enable: true

spring:
  application:
    name: film

  datasource:
    url: jdbc:postgresql://localhost:5432/films
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  
  kafka:
    bootstrap-servers: localhost:9092
    topic-return: returned-film
    topic-rent: rent-film
    group-return: group-return
    group-rent: group-rent
    
  client:
    url: http://localhost:8082/client-api/client/

eureka:
  client:
    instance.preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true

    serviceUrl:
aaass      defaultZone: http://localhost:8761/eureka
      