app:
  jwt-expiration-milliseconds: 86400000
  jwt-secret: JwtSecret

debug:
  enable: true

eureka:
  client:
    fetchRegistry: true
    instance:
        preferIpAddress: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    routes:
      enable: true
      enabled: true
    web:
      exposure:
        include: *

server:
  port: 9093

spring:
  application:
      name: gateway
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
  main:
    web-application-type: reactive
    
  user:
    username:
      url: http://user-service:8083/api/user/username/