app:
  jwt-expiration-milliseconds: 86400000
  jwt-secret: JwtSecret

debug:
  enable: true

eureka:
  client:
    fetchRegistry: true
    instance:
        preferIpAddress: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    routes:
      enable: true
      enabled: true
    web:
      exposure:
        include: "*"

server:
  port: 9093

spring:
  application:
      name: gateway
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8080/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://keycloak:8080/auth/realms/master/protocol/openid-connect/auth
            userinfo-uri: http://keycloak:8080/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: c6480137-1526-4c3e-aed3-295aabcb7609
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
          keycloak-without-test-scope:
            provider: keycloak
            client-id: spring-without-test-scope
            client-secret: f6fc369d-49ce-4132-8282-5b5d413eba23
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

  main:
    web-application-type: reactive
    
  user:
    username:
      url: http://user-service:8083/api/user/username/