app:
  jwt-expiration-milliseconds: 86400000
  jwt-secret: JwtSecret

debug:
  enable: true

eureka:
  client:
    fetchRegistry: true
    instance:
        preferIpAddress: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    routes:
      enable: true
      enabled: true
    web:
      exposure:
        include: "*"

server:
  port: 9093

spring:
  application:
      name: gateway
  cloud:
      gateway:
        default-filters:
          - TokenRelay=
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true

  security:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/auth/realms/JJRealm
        registration:
          quotes-client:
            provider: keycloak
            client-id: spring-gateway-client
            client-secret: secret

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    
  user:
    username:
      url: http://user-service:8083/api/user/username/